# -*- coding: utf-8 -*-
"""Likhitha.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZfDWQTKX_ZFNNY5WVqt8ixTasN3mjFXA
"""

arr = [2, 3, 4, 5, 6];     
print("Original array: ");    
for i in range(0, len(arr)):    
    print(arr[i]),     
print("Array in reverse order: ");        
for i in range(len(arr)-1, -1, -1):     
    print(arr[i]),

"""write a python program to print the element of an array in reverse order"""