# -*- coding: utf-8 -*-
"""Likhitha.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zil6kRFZjYGILllN60YkFzjDGL42lk9H
"""

n_terms = int(input ("How many terms the user wants to print? "))
n_1 = 0 
n_2 = 1
count = 0
if n_terms <= 0:
   print("Please enter a positive integer")
elif n_terms == 1:
   print("Fibonacci sequence upto",n_terms,":")
   print(n1)
else:
   print("Fibonacci sequence:")
   while count < n_terms:
       print(n1)
       nth = n1 + n2 
       n1 = n2
       n2 = nth
       count += 1

"""write a python program for fibonacci series"""